---
- name: Patch systems
  hosts: patch
  become: yes

  tasks:

  - name: upgrade all packages for RedHat systems
    yum:
      name: '*'
      state: latest
    when: ansible_facts['os_family'] == "RedHat"

  - name: Upgrade all packages for Debian systems
    apt:
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == "Debian"
