---
  - name: secret_play
    hosts: app01
    become: yes 
    vars:
      #set the variable 
      secret_root_password : password 

    tasks:
      - name: Secret Stuff 
        command: "echo {{ secret_root_password }} | sudo su -"
        no_log: true
