---
  - name: simple_var
    hosts: app01
    become: yes 
    vars:
      #set the variable 
      remote_install_path: "/opt/my_app_config"

    tasks:
      - name: Reture the set path
        debug:
          msg: path {{ remote_install_path }}
