---
  - name: simple_dict
    hosts: app01
    become: yes 
    vars:
      #set the variable 
      debug: "true" 

    tasks:
      - name: Print the log level 
        debug:
          msg: "Debug is set to {{ debug }}"
