---
  - name: vars_playbook
    hosts: webserver
    remote_user: vagrant
    become: yes
    become_user: root

    tasks:
      - name: ensure base packages are installed
        apt:
          pkg:
            - apache2

      - name: Install index.html
        template:
          src: "../templates/index.html.j2"
          dest: /var/www/html/index.html
          mode: 0777
