---
  - name: vars_playbook
    hosts: all
    remote_user: vagrant
    become: yes
    become_user: root

    vars:
      user: admin

    tasks:

      - name: Add the user 'admin' with a bash shell, appending the group 'adm'
        user:
          name: "{{ user }}"
          shell: /bin/bash
          groups: adm
          append: yes
  
      - name: Return users part of adm 
        shell: cat /etc/group | grep -w adm
        register: passwd_results

      - name: Gathering ansible facts 
        debug:
          msg: Users found in adm group for {{ ansible_hostname }} is {{ passwd_results.stdout }} 
